server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rating
    username: root
    password: system890
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
